---
title: "Precard Data Exploration"
author: "Tasos Mangelis" 
date: "15.05.2022" 
output:
  powerpoint_presentation:
    reference_doc: my-styles.pptx
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(collapse = TRUE,comment = "#>")

library("DataExplorer")
library(pander)
library(knitr)
library(summarytools)
library(gtsummary)
library(ggplot2)
library(stringr)

```


# 1. Summary statistics 

## Check data types and missing value counts
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=8}
str(precard_DTI)%>%kable()
```

## Quick data overview

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=8}
summary(precard_DTI)%>%kable()
```

# 2. Check missing data

## Missing data visual

```{r echo=FALSE, message=FALSE, warning=FALSE, results='markup'}
plot_missing(precard_DTI)
```

## Further visualisation to check for potential correlation
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=8}
naniar::vis_miss(precard_DTI%>%sample_frac(0.2))
```

# 3. Check validity of imputation

## Density plot (mice)
```{r echo=FALSE, message=FALSE, warning=FALSE, results="markup", fig.height=6, fig.width=8}
# check the imputation results by overlaying density plots of the old distribution against the new
mice::densityplot(prediction)
```

# 4. Further plots

## Histograms

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=8}
plot_histogram(precard_DTI_full)
```

## Correlations 

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=8}
# Check for correlations between all variables with visual representation
plot_correlation(precard_DTI_full)

```


# End of code ----