---
title: "Precardc_BaselineData"
author: "Tasos"
date: "14/04/2020"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 8
    fig_width: 10
    number_sections: yes
    toc: yes

---

```{r echo=FALSE, message=FALSE, warning=FALSE, comment=""}
# Load necessary libraries
library("DataExplorer")
library("gtsummary")
```

# Plots for total dataset visualisations

## Missing data

```{r echo=FALSE, message=FALSE, warning=FALSE, comment="", results='asis'}
# This gives a plot of missing data including their percentage in the total dataset
# Useful for identification of variables to exclude 
plot_missing(precard_merged)

```

## Bar plots

```{r echo=FALSE, message=FALSE, warning=FALSE, comment="", results='asis'}
# Plot bar plots to get a feeling of categorical data distributions
plot_bar(precard_merged)

```

## Box plots

```{r echo=FALSE, message=FALSE, warning=FALSE, comment="", results='asis'}
# Boxplots and histograms below will give us an idea about the extreme points and 
# distributions of the variable within the data
plot_boxplot(data =  precard_merged, by = "DM_TYPE_ID", nrow = 2, ncol =4)

```

## Histograms 

```{r echo=FALSE, message=FALSE, warning=FALSE, comment="", results='asis'}

plot_histogram(precard_merged, nrow = 2, ncol = 4)

```

## Statistics of numerical variables at baseline by diabetes type

```{r echo=FALSE, message=FALSE, warning=FALSE, comment="", results='asis'}

# Use the gtsummary() function  to create a table of all variables, 
# split between type 1 and type 2 datasets

precard_merged%>%
  # Identify and get the baseline data only
  group_by(R50_ID)%>%arrange(TEST_DATE)%>%slice(1)%>%ungroup()%>%
  select(Gender, Ethnicity_groups, eGFR_bsl, DM_TYPE_ID, Age, Diabetes_Dur, Weight, BMI, Hba1c, Cholesterol, SYSTOLIC, DIASTOLIC, HDL, LDL, Triglycerids, RM)%>%
  tbl_summary(by = DM_TYPE_ID, # Stratify by diabetes type
              # Define which statistics will be calculated and displayed
              statistic = list(all_continuous() ~ "{mean} ({sd}), {median} ({p25}, {p75})",
                              all_categorical() ~ "{n} ({p}%)"), 
              # Defien digits for those numbers
              digits = list(all_categorical() ~ c(0, 1), 
                            all_continuous() ~ c(0,1)))%>%
  add_overall()%>% # Since we are stratifying, this displays total numbers before stratification
  add_p() # Adds comparisons between groups


```

# End of code ----